# AUTOGENERATED! DO NOT EDIT! File to edit: nb_train.metrics.ipynb (unless otherwise specified).

__all__ = ['sensitivity', 'specificity']

# Cell
from fastai.vision.all import *

# Cell
sensitivity = Recall()
specificity = Recall(pos_label=0)