# AUTOGENERATED! DO NOT EDIT! File to edit: 01_utils.general.ipynb (unless otherwise specified).

__all__ = ['load_config_yaml']

# Cell
import yaml
from pathlib import Path
import os

# Cell
def load_config_yaml(path_to_yaml):
    '''Load project config yaml and change relative paths to absolute paths'''

    with open(path_to_yaml) as file:
        config = yaml.load(file, Loader=yaml.FullLoader)

    parent_dir = Path(os.path.dirname(os.getcwd()))
    for k, v in config.items():
        if "path" in k:
            config[k] = parent_dir/v
    return config