# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"downsample_df": "00_train.balance.ipynb",
         "upsample_df": "00_train.balance.ipynb",
         "balance_df": "00_train.balance.ipynb"}

modules = ["train/balance.py"]

doc_url = "https://maronr.github.io/scp_helpers/"

git_url = "https://github.com/maronr/scp_helpers/tree/master/"

def custom_doc_links(name): return None
