# AUTOGENERATED! DO NOT EDIT! File to edit: 01_utils.general.ipynb (unless otherwise specified).

__all__ = ['load_config_yaml', 'p2t', 't2p', 'a2p']

# Cell
import yaml
import os
import torchvision
import PIL
from pathlib import Path

# Cell
def load_config_yaml(path_to_yaml):
    '''Load project config yaml and change relative paths to absolute paths'''

    with open(path_to_yaml) as file:
        config = yaml.load(file, Loader=yaml.FullLoader)

    parent_dir = Path(os.path.dirname(os.getcwd()))
    for k, v in config.items():
        if "path" in k:
            config[k] = parent_dir/v
    return config

# Cell
p2t = torchvision.transforms.ToTensor()
t2p = torchvision.transforms.ToPILImage()
a2p = PIL.Image.fromarray